# Generated by Django 3.2.3 on 2023-07-02 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientcompany',
            options={},
        ),
        migrations.AlterModelOptions(
            name='pelclient',
            options={},
        ),
    ]
